"""rename column name_character -> name

Revision ID: 4da9680b6880
Revises: f11f58772345
Create Date: 2026-05-07 13:24:40.388220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da9680b6880'
down_revision: Union[str, Sequence[str], None] = 'f11f58772345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasheets', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('datasheets', 'name_character')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasheets', sa.Column('name_character', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('datasheets', 'name')
    # ### end Alembic commands ###
