"""add rulesets table

Revision ID: 85589ad63686
Revises: efcc8e5d7056
Create Date: 2026-05-31 11:45:39.843087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85589ad63686'
down_revision: Union[str, Sequence[str], None] = 'efcc8e5d7056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulesets',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('owner_uuid', sa.UUID(), nullable=True),
    sa.Column('parent_uuid', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='общедоступная книга правил'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_uuid'], ['rulesets.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rulesets')
    # ### end Alembic commands ###
