"""add timestamps into datasheets

Revision ID: efcc8e5d7056
Revises: 4da9680b6880
Create Date: 2026-05-07 14:05:11.389443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcc8e5d7056'
down_revision: Union[str, Sequence[str], None] = '4da9680b6880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasheets', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('datasheets', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasheets', 'updated_at')
    op.drop_column('datasheets', 'created_at')
    # ### end Alembic commands ###
