"""edit datasheet table

Revision ID: f11f58772345
Revises: ef50d7d1fa7e
Create Date: 2026-05-07 13:22:14.141760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f11f58772345'
down_revision: Union[str, Sequence[str], None] = 'ef50d7d1fa7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasheets', sa.Column('stats', sa.JSON(), nullable=False))
    op.add_column('datasheets', sa.Column('features', sa.JSON(), nullable=False, comment='черты персонажа'))
    op.drop_column('datasheets', 'skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasheets', sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('datasheets', 'features')
    op.drop_column('datasheets', 'stats')
    # ### end Alembic commands ###
